# Python PROD values.yaml
replicaCount: 5

podDisruptionBudget:
  enabled: true
  minAvailable: 2

resources:
  requests:
    cpu: 256m
    memory: 512Mi
  limits:
    cpu: 512m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: python-app-chart
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: python-app-chart

env:
  - name: APP_ENV
    value: "PRODUCTION"
