apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/apps/nodejs/release.yaml
  - ../../base/apps/python/release.yaml
  - ../../base/sources/main-repo.yaml

patches:
  - target:
      kind: HelmRelease
      name: nodejs-app
    patch: |
      - op: replace
        path: /metadata/name
        value: nodejs-app-stag
      - op: replace
        path: /metadata/namespace
        value: nodejs-app-stag
      - op: add
        path: /spec/values
        value:
          replicaCount: 3
          env:
            - name: APP_ENV
              value: "STAGING"
  - target:
      kind: HelmRelease
      name: python-app
    patch: |
      - op: replace
        path: /metadata/name
        value: python-app-stag
      - op: replace
        path: /metadata/namespace
        value: python-app-stag
      - op: add
        path: /spec/values
        value:
          replicaCount: 3
          env:
            - name: APP_ENV
              value: "STAGING"
