apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-stag
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<your-username>/k-helm-charts.git'
    targetRevision: HEAD
    path: python-app-chart
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/<your-username>/k-platform-deploy/main/argocd-app-python/environments/stag/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: python-app-stag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
